use_frameworks!

target 'QFLibrary_Example' do
  pod 'QFLibrary', :path => '../'

  target 'QFLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
